### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by DJNotOkay** [pot-noodle-python/discord-auto-reply#1]
after inputting the proper token, it asks me to enter valid credentials

**Comment by pot-noodle-python** [comment]
I will work on fixing this. I have unlisted the YouTube video while I'm fixing

**Comment by DJNotOkay** [comment]
> I will work on fixing this. I have unlisted the YouTube video while I'm fixing

thanks!

**Comment by LordXenaroth** [comment]
I have this same issue

**Comment by pot-noodle-python** [comment]
Sorry guys, been caught up with lots of other stuff. I'll try fix this issue but no promises

**Comment by pot-noodle-python** [comment]
Fixed issue.
