### ISSUE TITLE
Keep getting "Please enter valid credentials"

### ISSUE THREAD

**Issue by omgfrost** [pot-noodle-python/discord-auto-reply#3]
![Efz9hJp 1](https://user-images.githubusercontent.com/14861120/124252677-7e0e3580-db27-11eb-9d30-47eebd08bc96.png)
How to fix this?
Thanks in advance

**Comment by srotter0** [comment]
I get the exact same error. Any way to fix?

**Comment by LlandynK** [comment]
Hi omgfrost,

You have to remove the quotations at the beginning and end of your token otherwise it wont work.
I hope it works after that!

**Comment by Vreslia** [comment]
im getting the error without this lol
